# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins
import svo.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_group', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('item_order', otree.db.models.StringField(max_length=10000, null=True)),
                ('svo1dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('svo2dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('svo3dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('svo4dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('svo5dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('svo6dec', svo.fields.SvoField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('mean_ego', otree.db.models.FloatField(null=True)),
                ('mean_alter', otree.db.models.FloatField(null=True)),
                ('svo1ego', otree.db.models.IntegerField(null=True)),
                ('svo2ego', otree.db.models.IntegerField(null=True)),
                ('svo3ego', otree.db.models.IntegerField(null=True)),
                ('svo4ego', otree.db.models.IntegerField(null=True)),
                ('svo5ego', otree.db.models.IntegerField(null=True)),
                ('svo6ego', otree.db.models.IntegerField(null=True)),
                ('svo1alter', otree.db.models.IntegerField(null=True)),
                ('svo2alter', otree.db.models.IntegerField(null=True)),
                ('svo3alter', otree.db.models.IntegerField(null=True)),
                ('svo4alter', otree.db.models.IntegerField(null=True)),
                ('svo5alter', otree.db.models.IntegerField(null=True)),
                ('svo6alter', otree.db.models.IntegerField(null=True)),
                ('svo_angle', otree.db.models.FloatField(null=True)),
                ('svo_type', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='svo.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_player', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svo_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo.Subsession'),
        ),
    ]
